### ISSUE TITLE
Dark mode has issues

### ISSUE THREAD

**Issue by SxxAq** [ankitpareek0141/Favorite-OTT-characters#26]
I want to work on dark mode as it doesnt look like dark mode bcz the 
card sections are still white.
please assign me this with hactoberfest label.
Thankyou!
it should look like this :
![image](https://user-images.githubusercontent.com/98530202/194096355-79960d90-eb48-40d7-a154-5ccc4232dec6.png)
but it looks like this in dark mode :
![image](https://user-images.githubusercontent.com/98530202/194096619-c670a46f-103f-4f53-962e-5b81062df715.png)

**Comment by Shubham-20205157** [comment]
Can You assign me this issue please, I want to contribute.
